---

- name: wait-for-reboot
  wait_for_connection:
    delay: "5"
    timeout: "300"

- name: Restart Monitorix
  service:
    name: monitorix
    state: restarted
  when: register_monitorix_config.changed
